/**
 * Pre-defined Service Templates for CS Practice
 * Comprehensive templates with custom fields for specialized services
 */

import { ServiceTemplateDefinition, FIELD_PATTERNS, VALIDATION_MESSAGES } from '@/types/custom-fields';

export const CS_SERVICE_TEMPLATES: ServiceTemplateDefinition[] = [
  // ===== COMPANY INCORPORATION =====
  {
    name: 'Company Incorporation',
    description: 'Complete company incorporation services including name approval and registration',
    defaultRate: 25000,
    gstRate: 18,
    hsnSac: '998399',
    category: 'CORPORATE',
    customFields: [
      {
        name: 'companyName',
        label: 'Company Name',
        type: 'text',
        required: true,
        placeholder: 'ABC Private Limited',
        helpText: 'Full legal name of the company',
        group: 'Company Details',
      },
      {
        name: 'cin',
        label: 'CIN',
        type: 'text',
        required: true,
        placeholder: 'U12345KA2020PTC123456',
        helpText: '21-character Corporate Identification Number',
        validation: {
          pattern: FIELD_PATTERNS.CIN.source,
          message: VALIDATION_MESSAGES.INVALID_CIN,
        },
        group: 'Company Details',
      },
      {
        name: 'registrationDate',
        label: 'Date of Incorporation',
        type: 'date',
        required: true,
        group: 'Company Details',
      },
      {
        name: 'authorizedCapital',
        label: 'Authorized Capital',
        type: 'currency',
        required: true,
        placeholder: '100000',
        helpText: 'Authorized share capital of the company',
        validation: {
          min: 100000,
          message: 'Minimum authorized capital is ₹1,00,000',
        },
        group: 'Financial Details',
      },
      {
        name: 'paidUpCapital',
        label: 'Paid-up Capital',
        type: 'currency',
        required: true,
        placeholder: '100000',
        helpText: 'Actual paid-up share capital',
        group: 'Financial Details',
      },
      {
        name: 'rocOffice',
        label: 'ROC Office',
        type: 'select',
        required: true,
        options: [
          'ROC Karnataka',
          'ROC Delhi',
          'ROC Mumbai',
          'ROC Chennai',
          'ROC Kolkata',
          'ROC Hyderabad',
          'ROC Pune',
          'ROC Ahmedabad',
        ],
        group: 'Registration Details',
      },
    ],
  },

  // ===== DIRECTOR APPOINTMENT =====
  {
    name: 'Director Appointment',
    description: 'Director appointment services including form filing and compliance',
    defaultRate: 5000,
    gstRate: 18,
    hsnSac: '998399',
    category: 'COMPLIANCE',
    customFields: [
      {
        name: 'directorName',
        label: 'Director Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
        group: 'Director Information',
      },
      {
        name: 'din',
        label: 'DIN',
        type: 'text',
        required: true,
        placeholder: '12345678',
        helpText: '8-digit Director Identification Number',
        validation: {
          pattern: FIELD_PATTERNS.DIN.source,
          message: VALIDATION_MESSAGES.INVALID_DIN,
        },
        group: 'Director Information',
      },
      {
        name: 'pan',
        label: 'PAN',
        type: 'text',
        required: false,
        placeholder: 'ABCDE1234F',
        validation: {
          pattern: FIELD_PATTERNS.PAN.source,
          message: VALIDATION_MESSAGES.INVALID_PAN,
        },
        group: 'Director Information',
      },
      {
        name: 'appointmentDate',
        label: 'Date of Appointment',
        type: 'date',
        required: true,
        group: 'Appointment Details',
      },
      {
        name: 'designation',
        label: 'Designation',
        type: 'select',
        required: true,
        options: [
          'Managing Director',
          'Whole-time Director',
          'Independent Director',
          'Non-Executive Director',
          'Additional Director',
          'Alternate Director',
          'Nominee Director',
        ],
        group: 'Appointment Details',
      },
      {
        name: 'formFiled',
        label: 'Form Filed',
        type: 'select',
        required: false,
        options: ['DIR-12', 'DIR-11', 'MGT-14'],
        group: 'Filing Details',
      },
    ],
  },

  // ===== ROC FORM FILING (MGT-7, AOC-4, etc.) =====
  {
    name: 'ROC Annual Filing',
    description: 'Annual ROC form filing services (MGT-7, AOC-4, ADT-1, etc.)',
    defaultRate: 8000,
    gstRate: 18,
    hsnSac: '998399',
    category: 'ANNUAL_COMPLIANCE',
    customFields: [
      {
        name: 'formNumber',
        label: 'Form Number',
        type: 'select',
        required: true,
        options: [
          'MGT-7 (Annual Return)',
          'AOC-4 (Financial Statements)',
          'ADT-1 (Auditor Appointment)',
          'DIR-3 KYC (Director KYC)',
          'MR-3 (MSME Return)',
          'DPT-3 (Deposit Return)',
          'MSME-1 (Half-yearly Return)',
        ],
        group: 'Form Details',
      },
      {
        name: 'financialYearEnd',
        label: 'Financial Year End Date',
        type: 'date',
        required: true,
        helpText: 'End date of the financial year (e.g., 31st March 2024)',
        group: 'Period Details',
      },
      {
        name: 'agmDate',
        label: 'AGM Date',
        type: 'date',
        required: false,
        helpText: 'Annual General Meeting date (if applicable)',
        group: 'Period Details',
      },
      {
        name: 'filingDate',
        label: 'Filing Date',
        type: 'date',
        required: false,
        helpText: 'Actual date of filing with ROC',
        group: 'Filing Details',
      },
      {
        name: 'srn',
        label: 'SRN (Service Request Number)',
        type: 'text',
        required: false,
        placeholder: 'A12345678901234',
        helpText: 'Service Request Number received after filing',
        group: 'Filing Details',
      },
      {
        name: 'filingFee',
        label: 'Filing Fee',
        type: 'currency',
        required: false,
        placeholder: '0',
        helpText: 'Government filing fee paid',
        group: 'Financial Details',
      },
      {
        name: 'additionalFee',
        label: 'Additional Fee',
        type: 'currency',
        required: false,
        placeholder: '0',
        helpText: 'Late filing fee or penalty (if any)',
        group: 'Financial Details',
      },
    ],
  },

  // ===== BOARD RESOLUTION =====
  {
    name: 'Board Resolution',
    description: 'Board resolution drafting and filing services',
    defaultRate: 3000,
    gstRate: 18,
    hsnSac: '998399',
    category: 'SECRETARIAL',
    customFields: [
      {
        name: 'resolutionNumber',
        label: 'Resolution Number',
        type: 'text',
        required: true,
        placeholder: 'BR-2024-001',
        helpText: 'Internal reference number for the resolution',
        group: 'Resolution Details',
      },
      {
        name: 'resolutionDate',
        label: 'Date of Resolution',
        type: 'date',
        required: true,
        group: 'Resolution Details',
      },
      {
        name: 'subject',
        label: 'Subject',
        type: 'textarea',
        required: true,
        placeholder: 'Appointment of statutory auditor...',
        helpText: 'Brief subject/purpose of the resolution',
        validation: {
          minLength: 10,
          maxLength: 500,
        },
        group: 'Resolution Details',
      },
      {
        name: 'resolutionType',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          'Board Resolution',
          'Circular Resolution',
          'Written Resolution',
          'Special Resolution',
        ],
        group: 'Resolution Details',
      },
      {
        name: 'formRequired',
        label: 'Form Filing Required',
        type: 'select',
        required: false,
        options: ['MGT-14', 'INC-28', 'Not Required'],
        helpText: 'ROC form to be filed for this resolution',
        group: 'Filing Requirements',
      },
    ],
  },

  // ===== SHARE TRANSFER =====
  {
    name: 'Share Transfer',
    description: 'Share transfer and transmission services',
    defaultRate: 2000,
    gstRate: 18,
    hsnSac: '998399',
    category: 'SECRETARIAL',
    customFields: [
      {
        name: 'transferorName',
        label: 'Transferor Name',
        type: 'text',
        required: true,
        placeholder: 'Name of the seller',
        group: 'Transfer Details',
      },
      {
        name: 'transfereeName',
        label: 'Transferee Name',
        type: 'text',
        required: true,
        placeholder: 'Name of the buyer',
        group: 'Transfer Details',
      },
      {
        name: 'folioNumber',
        label: 'Folio Number',
        type: 'text',
        required: true,
        placeholder: 'F-001',
        group: 'Share Details',
      },
      {
        name: 'certificateNumbers',
        label: 'Share Certificate Numbers',
        type: 'text',
        required: true,
        placeholder: 'SC-001, SC-002',
        helpText: 'Comma-separated certificate numbers',
        group: 'Share Details',
      },
      {
        name: 'numberOfShares',
        label: 'Number of Shares',
        type: 'number',
        required: true,
        placeholder: '100',
        validation: {
          min: 1,
          message: 'At least 1 share must be transferred',
        },
        group: 'Share Details',
      },
      {
        name: 'considerationAmount',
        label: 'Consideration Amount',
        type: 'currency',
        required: false,
        placeholder: '0',
        helpText: 'Transfer consideration (if any)',
        group: 'Financial Details',
      },
      {
        name: 'transferDate',
        label: 'Date of Transfer',
        type: 'date',
        required: true,
        group: 'Transfer Details',
      },
    ],
  },

  // ===== COMPLIANCE CERTIFICATE =====
  {
    name: 'Compliance Certificate',
    description: 'Secretarial compliance certificate and annual certificate issuance',
    defaultRate: 15000,
    gstRate: 18,
    hsnSac: '998399',
    category: 'AUDIT',
    customFields: [
      {
        name: 'certificateType',
        label: 'Certificate Type',
        type: 'select',
        required: true,
        options: [
          'Annual Secretarial Compliance Certificate',
          'Statutory Compliance Certificate',
          'Reconciliation of Share Capital',
          'LODR Compliance Certificate',
        ],
        group: 'Certificate Details',
      },
      {
        name: 'certificateNumber',
        label: 'Certificate Number',
        type: 'text',
        required: true,
        placeholder: 'CERT-2024-001',
        group: 'Certificate Details',
      },
      {
        name: 'issueDate',
        label: 'Date of Issue',
        type: 'date',
        required: true,
        group: 'Certificate Details',
      },
      {
        name: 'periodFrom',
        label: 'Period From',
        type: 'date',
        required: true,
        helpText: 'Start date of compliance period',
        group: 'Period Details',
      },
      {
        name: 'periodTo',
        label: 'Period To',
        type: 'date',
        required: true,
        helpText: 'End date of compliance period',
        group: 'Period Details',
      },
      {
        name: 'validityPeriod',
        label: 'Validity Period',
        type: 'text',
        required: false,
        placeholder: '1 year from date of issue',
        group: 'Certificate Details',
      },
    ],
  },

  // ===== AGM SERVICES =====
  {
    name: 'AGM Conduct & Compliance',
    description: 'Annual General Meeting conduct and compliance services',
    defaultRate: 10000,
    gstRate: 18,
    hsnSac: '998399',
    category: 'SECRETARIAL',
    customFields: [
      {
        name: 'agmDate',
        label: 'AGM Date',
        type: 'date',
        required: true,
        group: 'Meeting Details',
      },
      {
        name: 'agmTime',
        label: 'AGM Time',
        type: 'text',
        required: false,
        placeholder: '11:00 AM',
        group: 'Meeting Details',
      },
      {
        name: 'venue',
        label: 'Venue',
        type: 'textarea',
        required: false,
        placeholder: 'Registered office address or virtual meeting link',
        validation: {
          maxLength: 200,
        },
        group: 'Meeting Details',
      },
      {
        name: 'financialYearEnd',
        label: 'Financial Year End',
        type: 'date',
        required: true,
        helpText: 'Financial year for which AGM is being conducted',
        group: 'Period Details',
      },
      {
        name: 'noticeDate',
        label: 'Notice Sent Date',
        type: 'date',
        required: false,
        helpText: 'Date when AGM notice was sent to members',
        group: 'Compliance Details',
      },
      {
        name: 'agmMode',
        label: 'AGM Mode',
        type: 'select',
        required: true,
        options: ['Physical', 'Virtual', 'Hybrid'],
        group: 'Meeting Details',
      },
    ],
  },

  // ===== LLP COMPLIANCE =====
  {
    name: 'LLP Annual Filing',
    description: 'Limited Liability Partnership annual compliance services',
    defaultRate: 5000,
    gstRate: 18,
    hsnSac: '998399',
    category: 'LLP_COMPLIANCE',
    customFields: [
      {
        name: 'llpin',
        label: 'LLPIN',
        type: 'text',
        required: true,
        placeholder: 'AAA-1234',
        helpText: 'Limited Liability Partnership Identification Number',
        group: 'LLP Details',
      },
      {
        name: 'formType',
        label: 'Form Type',
        type: 'select',
        required: true,
        options: [
          'Form 8 (Statement of Account & Solvency)',
          'Form 11 (Annual Return)',
          'Form 3 (Partner Appointment)',
          'Form 4 (Partner Cessation)',
        ],
        group: 'Filing Details',
      },
      {
        name: 'financialYearEnd',
        label: 'Financial Year End',
        type: 'date',
        required: true,
        group: 'Period Details',
      },
      {
        name: 'filingDate',
        label: 'Filing Date',
        type: 'date',
        required: false,
        group: 'Filing Details',
      },
      {
        name: 'srn',
        label: 'SRN',
        type: 'text',
        required: false,
        placeholder: 'Service Request Number',
        group: 'Filing Details',
      },
    ],
  },

  // ===== TRADEMARK SERVICES =====
  {
    name: 'Trademark Registration',
    description: 'Trademark search, application, and registration services',
    defaultRate: 7000,
    gstRate: 18,
    hsnSac: '998399',
    category: 'IP_SERVICES',
    customFields: [
      {
        name: 'trademarkName',
        label: 'Trademark Name/Logo',
        type: 'text',
        required: true,
        placeholder: 'Brand name or logo description',
        group: 'Trademark Details',
      },
      {
        name: 'applicantName',
        label: 'Applicant Name',
        type: 'text',
        required: true,
        group: 'Applicant Details',
      },
      {
        name: 'class',
        label: 'Class(es)',
        type: 'text',
        required: true,
        placeholder: '35, 42',
        helpText: 'Trademark class numbers (comma-separated)',
        group: 'Trademark Details',
      },
      {
        name: 'applicationNumber',
        label: 'Application Number',
        type: 'text',
        required: false,
        placeholder: 'TM application number',
        group: 'Application Details',
      },
      {
        name: 'applicationDate',
        label: 'Application Date',
        type: 'date',
        required: false,
        group: 'Application Details',
      },
      {
        name: 'registrationNumber',
        label: 'Registration Number',
        type: 'text',
        required: false,
        placeholder: 'After registration',
        group: 'Registration Details',
      },
      {
        name: 'registrationDate',
        label: 'Registration Date',
        type: 'date',
        required: false,
        group: 'Registration Details',
      },
    ],
  },

  // ===== STATUTORY AUDIT =====
  {
    name: 'Statutory Audit Coordination',
    description: 'Coordination and assistance for statutory audit compliance',
    defaultRate: 12000,
    gstRate: 18,
    hsnSac: '998399',
    category: 'AUDIT',
    customFields: [
      {
        name: 'auditFirmName',
        label: 'Audit Firm Name',
        type: 'text',
        required: true,
        placeholder: 'XYZ & Associates',
        group: 'Auditor Details',
      },
      {
        name: 'auditorName',
        label: 'Lead Auditor Name',
        type: 'text',
        required: false,
        group: 'Auditor Details',
      },
      {
        name: 'financialYearEnd',
        label: 'Financial Year End',
        type: 'date',
        required: true,
        group: 'Audit Period',
      },
      {
        name: 'auditStartDate',
        label: 'Audit Start Date',
        type: 'date',
        required: false,
        group: 'Audit Period',
      },
      {
        name: 'auditCompletionDate',
        label: 'Audit Completion Date',
        type: 'date',
        required: false,
        group: 'Audit Period',
      },
      {
        name: 'reportDate',
        label: 'Audit Report Date',
        type: 'date',
        required: false,
        group: 'Report Details',
      },
      {
        name: 'auditOpinion',
        label: 'Audit Opinion',
        type: 'select',
        required: false,
        options: [
          'Unmodified (Clean)',
          'Qualified',
          'Adverse',
          'Disclaimer',
        ],
        group: 'Report Details',
      },
    ],
  },
];

// Utility: Get template by name
export function getTemplateByName(name: string): ServiceTemplateDefinition | undefined {
  return CS_SERVICE_TEMPLATES.find((t) => t.name === name);
}

// Utility: Get all template names
export function getAllTemplateNames(): string[] {
  return CS_SERVICE_TEMPLATES.map((t) => t.name);
}

// Utility: Get templates by category
export function getTemplatesByCategory(category: string): ServiceTemplateDefinition[] {
  return CS_SERVICE_TEMPLATES.filter((t) => t.category === category);
}

// Categories available
export const SERVICE_CATEGORIES = [
  'CORPORATE',
  'COMPLIANCE',
  'ANNUAL_COMPLIANCE',
  'SECRETARIAL',
  'AUDIT',
  'LLP_COMPLIANCE',
  'IP_SERVICES',
] as const;
